animal = ("zebra", "alligator", "giraffe", "goat", "ox")
listofAnimals = list(animal)
print(listofAnimals)
listofAnimals.append("honey badger")
print(listofAnimals)
myString = "Hello! I am pleased to meet you"
newString = list(myString)
print(newString)
newString = myString.split(" ")
print(newString)
